// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package embedded

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Rootkey              []byte   `protobuf:"bytes,1,opt,name=rootkey,proto3" json:"rootkey,omitempty"`
	RootkeyPw            []byte   `protobuf:"bytes,2,opt,name=rootkey_pw,json=rootkeyPw,proto3" json:"rootkey_pw,omitempty"`
	Rootcert             []byte   `protobuf:"bytes,3,opt,name=rootcert,proto3" json:"rootcert,omitempty"`
	Apikey               string   `protobuf:"bytes,4,opt,name=apikey,proto3" json:"apikey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetRootkey() []byte {
	if m != nil {
		return m.Rootkey
	}
	return nil
}

func (m *Config) GetRootkeyPw() []byte {
	if m != nil {
		return m.RootkeyPw
	}
	return nil
}

func (m *Config) GetRootcert() []byte {
	if m != nil {
		return m.Rootcert
	}
	return nil
}

func (m *Config) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "embedded.Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xcd, 0x4d, 0x4a, 0x4d, 0x49,
	0x49, 0x4d, 0x51, 0x2a, 0xe5, 0x62, 0x73, 0x06, 0xcb, 0x08, 0x49, 0x70, 0xb1, 0x17, 0xe5, 0xe7,
	0x97, 0x64, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xc1, 0xb8, 0x42, 0xb2, 0x5c,
	0x5c, 0x50, 0x66, 0x7c, 0x41, 0xb9, 0x04, 0x13, 0x58, 0x92, 0x13, 0x2a, 0x12, 0x50, 0x2e, 0x24,
	0xc5, 0xc5, 0x01, 0xe2, 0x24, 0xa7, 0x16, 0x95, 0x48, 0x30, 0x83, 0x25, 0xe1, 0x7c, 0x21, 0x31,
	0x2e, 0xb6, 0xc4, 0x82, 0x4c, 0x90, 0x99, 0x2c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x5e, 0x12,
	0x1b, 0xd8, 0x1d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x34, 0x99, 0xed, 0x97, 0x00,
	0x00, 0x00,
}
